nodeLinker: pnpm

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  "eslint-plugin-import@*":
    peerDependencies:
      eslint-import-resolver-typescript: "*"
    peerDependenciesMeta:
      eslint-import-resolver-typescript:
        optional: true