name: CI

on:
  pull_request:
    branches-ignore:
      - "renovate/**"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: yarn tsc
      - run: yarn docker:typeorm migration:run
      - run: yarn migration:generate ItShouldNotHaveAnyDiffBetweenMigarationsAndSchema && git diff --exit-code
